LfMerge build produces container instead of .deb files
sillsdev/LfMerge pull request #186
Opened 2022-02-08 09:34 UTC by rmunn

Closes #185.

The basic way this works is that the `debian/rules` file (a Makefile that has to have specifically-named targets for the Debian build process to process it) is converted to a shell script. It puts the compilation results into place in a `tarball` directory, which is then copied into a new Docker image.

Roadmap for this PR before I mark it ready for review:

* [ ] Test the built lfmerge container locally
* [ ] Edit GHA workflow to push the built container to Docker Hub

2022-02-10 18:03 UTC, longrunningprocess requested changes
I'm really excited about this effort, it will be a really valuable refactor!

Most of my thoughts were relatively stylistic and some were questioning a possible oversight on your part but the workflow is really complex and I'd like to see some of those changes unless you want to discuss them further.

2022-02-11 03:39 UTC, rmunn commented on .github/workflows/docker-build.yml
> +        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
With [many](https://github.com/faisalman/ua-parser-js/issues/536) different [cases](https://blog.sonatype.com/newly-found-npm-malware-mines-cryptocurrency-on-windows-linux-macos-devices) of [hijacked](https://heimdalsecurity.com/blog/coa-and-rc-npm-packages-hijacked/) NPM packages, we **absolutely should not** be trusting that Github Actions packages won't ever be hijacked either. In fact, I plan to submit a PR replacing all the version numbers in the web-languageforge workflows with commit hashes, too.

2022-02-11 03:39 UTC, rmunn commented on .github/workflows/docker-build.yml
> +        env:
Why pass them through env? Because if the branch name happens to contain a `$` or `|` or `>` character, or even a `"` or `'` character, direct text replacement like `echo FW8 was ${{ needs.calculate_branches.outputs.FW8Branch }}` would end up having unintended effects and likely causing the build to fail. Passing the data in through environment variables ensures that special characters will get quoted correctly. There's a mention of this somewhere in the Github Actions docs, but I couldn't find it off-hand. But that's the reason: so that if someone, whether naïve or malicious, creates a branch named `John's testing branch` or `| tee /dev/null` or something, it won't cause a syntax error in the build.

2022-02-11 03:39 UTC, rmunn commented on .github/workflows/docker-build.yml
> +          file: Dockerfile
The action was failing, which is why I added this, but it turned out to be failing for a different reason. I can remove this one.

2022-02-11 03:39 UTC, rmunn commented on .github/workflows/docker-build.yml
> +    # if: github.event_name == 'push' && (github.ref == 'refs/heads/live' || github.ref == 'refs/heads/fieldworks8-live')
Yes. Once I change the `push: false` input on the docker-build-push action, as described below, I will remove this line.

2022-02-11 03:39 UTC, rmunn commented on .github/workflows/docker-build.yml
> +      run: echo "$METADATA"
With passing the values through env, this allows them to be quoted correctly. Direct text substitution into the `echo` command would be unpredictable since I don't know what special characters will end up being in the metadata.

2022-02-11 03:39 UTC, rmunn commented on Dockerfile.finalresult
> +# logrotate - TODO: is this required?
Not yet; I plan to make that determination later, after I've merged the container build PR.

2022-02-11 03:39 UTC, rmunn commented on Dockerfile.finalresult
> +# TODO: Turn this into environment variables, because we want to be able to just set env vars in k8s config and restart the container
"this" is the sendreceive.conf file in the next line. Later on, you comment on wanting to replace it with env vars; I agree, as you can see from this comment.

2022-02-11 03:39 UTC, rmunn commented on docker/scripts/build-and-test.sh
> +# "$SCRIPT_DIR"/build-debpackages-combined.sh ${DbVersion}
Nope. Now that I know the container build is working, I can remove it.

2022-02-11 03:39 UTC, rmunn commented on docker/scripts/create-installation-tarball.sh
> +mkdir -p ${COMMONDESTDIR}/var/lib/languageforge/lexicon/sendreceive/state
Yes, that would work better. The original lines came from a Makefile, where perhaps the `{ }` shell syntax wasn't available, hence the way it was written. I'll replace this with a single line (and also add `syncqueue`, which was missing from the original).

2022-02-11 03:39 UTC, rmunn commented on lfmerge.conf
> +# Configuration file for LfMerge
Agreed, which is why I wrote that comment in the Dockerfile about "replac[ing] this with environment variables". (The "this" being this file.)

2022-02-11 03:39 UTC, rmunn commented on lfmergeqm-background.sh
> +#!/bin/sh
Good idea. After I merge this PR, I'll figure out how to do that.

2022-02-11 03:39 UTC, rmunn commented on lfmergeqm-looping.sh
> +#!/bin/sh
inotifywait is using the exact same system as https://github.com/longrunningprocess/docker-sandbox/tree/main/fs-watcher (which uses `inotifyd`). And I'm having a bit of trouble picturing how the inotify process would kick off lfmerge if it was in a separate container from the lfmerge container. And anyway, the whole point of this PR is to make the lfmerge container be a stand-alone container with volume mapping. I'm not sure that moving one tiny piece of it into a different container is a win.

2022-02-11 03:39 UTC, rmunn commented on mercurial-cacerts.rc
> +[web]
This config file is normally created by the `mercurial` package, which we don't install in the stripped-down `lfmerge` container. But without this config file, Send/Receive fails because Mercurial says "I can't verify the HTTPS fingerprint coming from the server". This config file points to the Debian-based list of certs that includes, among others, the LetsEncrypt root certs, so that our hg-public server can be verified.

In other words, this is required for Send/Receive to work, and it's better to just add this one file than the whole `mercurial` package.

2022-02-11 03:51 UTC, rmunn commented on .github/workflows/docker-build.yml
> +        env:
Found it: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable (also read the whole article)

2022-02-11 03:55 UTC, rmunn commented on .github/workflows/docker-build.yml
> +        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
Also, https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses says that "Using the commit SHA of a released action version is the safest for stability and security."

2022-02-11 04:06 UTC, rmunn commented on .github/workflows/docker-build.yml
> +          ./calculate-branches.sh | grep FW.Branch >> "${GITHUB_ENV}"
When FW 10 comes out, I'll need to change these to FW08 and FW09 and make the regex `FW..Branch`, with two dots instead of one. But that won't happen for a few more years, and it's more likely that I'll change the build process again before that happens.

2022-02-11 04:07 UTC, megahirt commented on .github/workflows/docker-build.yml
> +        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
Robin and I discussed this in the office and we will compromise with pinning it to the specific version number v2.0.10

2022-02-11 04:17 UTC, rmunn commented on .github/workflows/docker-build.yml
> +        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
After discussing this with Chris, I'll switch the actions that are official GitHub actions (`actions/checkout` and `actions/(up|down)load-artifacts`) to use version numbers, because it's so extremely unlikely that the official GitHub `actions` repositories will ever be hijacked. I'll keep using commit SHAs for the `docker/foo` actions, because there, I don't know how many people have access to the `docker` org account and how quickly it would be noticed if someone hijacked it. But with the official Microsoft-owned `actions` org, I'll acknowledge that the commit SHAs are probably more paranoid than is strictly necessary.

2022-02-11 04:18 UTC, rmunn commented on .github/workflows/docker-build.yml
> +      run: echo "$METADATA"
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable explains why I did this. I would keep this one as-is as far as the env vars go, except that I'll end up removing it because it's debugging output that I don't need anymore.

2022-02-11 04:22 UTC, rmunn commented on Dockerfile.finalresult
> +# logrotate - TODO: is this required?
Talked to Tim Eves, who said "Keep it". Because while at the moment the logs never get that big because the container is frequently deleted and re-created (every time we push a new LF deployment), there will come a day when the site goes into maintenance mode for a while. And then the logs will just accumulate, and might end up eating up all the space allocation for the pod. Using `logrotate` (which might require adding a config file or two) will allow us to delete old logs automatically, to ensure that we don't fill up the container. So I'll remove this TODO comment and keep the `logrotate` package.

2022-02-11 04:55 UTC, merged

2022-02-11 18:00 UTC, longrunningprocess commented on .github/workflows/docker-build.yml
> +        env:
lots of good advice in there, thanks

2022-02-11 18:09 UTC, longrunningprocess commented on .github/workflows/docker-build.yml
>    workflow_dispatch:
I'm not sure you'll need this capability, might be better to simply remove it.

2022-02-11 18:09 UTC, longrunningprocess commented on .github/workflows/docker-build.yml
> +        env:
based on the triggers, maybe there's a disconnect here between what can trigger this workflow and what might appear in the output of your script?  Is it because of something that happens in your script that you now don't trust it?

2022-02-11 18:10 UTC, longrunningprocess commented on .github/workflows/docker-build.yml
> +          file: Dockerfile
great, thanks

2022-02-11 18:10 UTC, longrunningprocess commented on .github/workflows/docker-build.yml
> +        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
sounds good

2022-02-11 18:11 UTC, longrunningprocess commented on .github/workflows/docker-build.yml
> +    # if: github.event_name == 'push' && (github.ref == 'refs/heads/live' || github.ref == 'refs/heads/fieldworks8-live')
ok

2022-02-11 18:11 UTC, longrunningprocess commented on Dockerfile.finalresult
> +# logrotate - TODO: is this required?
ok

2022-02-11 18:12 UTC, longrunningprocess commented on docker/scripts/build-and-test.sh
> +# "$SCRIPT_DIR"/build-debpackages-combined.sh ${DbVersion}
great

2022-02-11 18:12 UTC, longrunningprocess commented on lfmerge.conf
> +# Configuration file for LfMerge
ok

2022-02-11 18:13 UTC, longrunningprocess commented on lfmergeqm-background.sh
> +#!/bin/sh
sounds like a good approach, maybe you could just capture it i another issue or however you're tracking your work.

2022-02-11 18:15 UTC, longrunningprocess commented on lfmergeqm-looping.sh
> +#!/bin/sh
that reference wasn't as much about inotify but the shared volume approach.  It would kick off via the dropzone (a shared volume)...we can talk about it if that will help clarify the idea.  Either way, it's another one in the same category as the background housekeeping conversation above, another issue for another time.

2022-02-11 18:16 UTC, longrunningprocess commented on mercurial-cacerts.rc
> +[web]
ok

2022-02-11 18:17 UTC, longrunningprocess commented on Dockerfile.finalresult
> +# logrotate - ensure logs won't grow without bound, and that old logs get cleaned up automatically
thank you!

2022-02-11 18:18 UTC, longrunningprocess commented
> @longrunningprocess I had a conversation in the office with @rmunn about his PR and your review. Thank you for your feedback and giving this review a go. In the interest of Robin moving forward on this project (there are a number of PRs waiting on this one) I agreed he should go ahead and merge without waiting for you to wake up and approve the PR.

understood