Set up end to end Send/Receive testing with LexBox
sillsdev/LfMerge pull request #342
Opened 2024-07-25 08:54 UTC by rmunn

WIP. Will fix https://github.com/sillsdev/LfMerge/issues/339 once completed.

This PR uses the LexBox API to set up end-to-end testing of Send/Receive scenarios.

**Currently implemented:**

* Reset project on LexBox to empty
* Upload new state of LexBox project
* Remove the last N commits from a LexBox project

**Future plans:**

* Implement liblcm helper class
* Start writing some real S/R tests

2024-08-19 04:53 UTC, rmunn commented
First end-to-end test is written and working. Doing self-review now, then will ask for code review.

2024-08-19 06:18 UTC, rmunn commented
The one failing test is the one this PR adds, with `HttpRequestException : Connection refused (localhost:80)`, from a previous `SocketException : Connection refused`. This is quite simply because the LfMerge GitHub workflow doesn't set up a copy of LexBox before running the tests. Before merging this PR, we might want to set up a local copy of LexBox, similarly to how https://github.com/sillsdev/languageforge-lexbox/pull/873 did it, so that the end-to-end tests can run.

Might want to split the test runs in two, actually; one runner will run the non-E2E tests with the current setup, and the other runner will set up a Kubernetes environment in GHA to run the E2E tests. That way the non-E2E tests can be run without paying the cost of setting up a k8s environment.

2024-08-19 07:05 UTC, rmunn commented
Okay, commit [779358e](https://github.com/sillsdev/LfMerge/commit/779358e507189c04e9c9d5c04cd890257a32dd60) demonstrates the race condition with hgweb's dir cache in local LexBox, and commit 80d45bba adjusts these tests to expect newly-created projects to sometimes not be available right away, avoiding the race condition. To test a potential fix in LexBox, use commit [779358e](https://github.com/sillsdev/LfMerge/commit/779358e507189c04e9c9d5c04cd890257a32dd60) and run `dotnet test --filter E2E_` repeatedly until you get test failures (shouldn't take long).

2024-08-20 08:58 UTC, hahn-kev requested changes
This looks like a great start. I think there's still a bit of work to do before we can merge it in. Inparticualr I'd like to make a bunch of the static code to be non static instead. Also it's not clear to me why we have both SRTest base and e2eTestBase and why one inherits from the other. I'd like to either merge those into one class, or just make one encapsulate the other.

2024-08-20 08:58 UTC, hahn-kev commented on src/LfMerge.Core.Tests/E2E/TryOutE2ETests.cs
> +			Guid entryId = Guid.Parse("0006f482-a078-4cef-9c5a-8bd35b53cf72");
rather than hardcoding a guid I'd like to see is fetch an entry from the db.

2024-08-20 08:58 UTC, hahn-kev commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +			var saveEnv = Environment.GetEnvironmentVariable(MagicStrings.SettingsEnvVar_LanguageDepotRepoUri);
uh, we can do better than this. We're passing in settings to the action below. Just modify LfMergeSettings so that it allows you to specify the repo Uri and then you don't need to mess around with environment variables.

2024-08-20 08:58 UTC, hahn-kev commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +	public class SRTestEnvironment : TestEnvironment
it looks like most of the code in this class is static, however it seems to be called from places that already have an instance of the environment. So I'd like that to be cleaned up. The environment stuff can stay static but everything else like the cookies and http clients etc should all be instance variables.

2024-08-20 08:58 UTC, hahn-kev commented on src/LfMerge.Core.Tests/SRTestBase.cs
> +	public class SRTestBase
this class says it's for e2e testing, but then there's another class that's called e2eTestBase which inherits from this. Do we really need to use inheritance here? I would rather not use inheritance where we can, especially since it's not clear what order all the setup and teardown methods are called in.

2024-08-20 08:58 UTC, hahn-kev commented on src/LfMerge.Core.Tests/TestDoubles.cs
> +			var envOverride = Environment.GetEnvironmentVariable(MagicStrings.SettingsEnvVar_LanguageDepotRepoUri);
this will break any test that is using the mock server, so if this variable is set during testing then those tests will fail

2024-08-21 02:16 UTC, rmunn commented on src/LfMerge.Core.Tests/TestDoubles.cs
> +			var envOverride = Environment.GetEnvironmentVariable(MagicStrings.SettingsEnvVar_LanguageDepotRepoUri);
That's the desired behavior, and I considered it a bug that ChorusHelperDouble wasn't honoring that environment variable.

This variable is designed for this purpose. and [is usually unset](https://github.com/sillsdev/LfMerge/blob/f518d8d925ae9c6fa53c856df519d425f15d27c1/src/LfMerge.Core/Settings/DefaultLfMergeSettings.cs#L20); the ChorusHelper class looks at the `settings.LanguageDepotRepoUri` value (which comes from this environment variable) and treats it as an override, allowing one to run a single test with a different destination than normal.

2024-08-21 04:28 UTC, rmunn commented on src/LfMerge.Core.Tests/TestDoubles.cs
> +			var envOverride = Environment.GetEnvironmentVariable(MagicStrings.SettingsEnvVar_LanguageDepotRepoUri);
However, I did change this to pull from LfMergeSettings instead of the environment variable, so that the override can be set on a per-test basis without messing with env vars (as you mentioned in https://github.com/sillsdev/LfMerge/pull/342#discussion_r1722940309).

2024-08-21 04:41 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +	public class SRTestEnvironment : TestEnvironment
I made the HTTP client static so that we'd only have to log in once, and the GQL client static because the docs recommended only using one instance and I didn't want to mess with DI while building the prototype. But if we're just running a single E2E test anyway, there's no cost to making these instance variables, at which point many of the static methods will become non-static. (I changed them to static at the recommendation of the compiler's code analysis suggestions, but many of them access the Http client so they'll soon become non-static again).

I do think I'm going to keep one thing static: the Jwt property, which I'll rename to AdminJwt. Then the Login method will become LoginAsAdmin, and it will first check if the static Jwt property is set. If so, it will insert a cookie with that Jwt into the instance-local cookie container, allowing us to still get the "just log in once and reuse that for all tests" effect.

2024-08-21 05:16 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +	public class SRTestEnvironment : TestEnvironment
Done in commit 3749cbe.

2024-08-21 05:18 UTC, rmunn commented on src/LfMerge.Core.Tests/TestDoubles.cs
> +			var envOverride = Environment.GetEnvironmentVariable(MagicStrings.SettingsEnvVar_LanguageDepotRepoUri);
Done in commit bea1713.

2024-08-21 05:18 UTC, rmunn commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +			var saveEnv = Environment.GetEnvironmentVariable(MagicStrings.SettingsEnvVar_LanguageDepotRepoUri);
Done in commit bea1713.

2024-08-21 05:21 UTC, rmunn commented on src/LfMerge.Core.Tests/E2E/TryOutE2ETests.cs
> +			Guid entryId = Guid.Parse("0006f482-a078-4cef-9c5a-8bd35b53cf72");
Done in commit 946468d.

2024-08-21 05:31 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestBase.cs
> +	public class SRTestBase
NUnit actually guarantees the order of setup and teardown methods across class inheritance; however, that's not necessarily going to hold true if we ever switch to a different test framework (e.g., XUnit doesn't use setup and teardown methods, preferring for you to put those in class constructors and Dispose() methods respectively).

But yes, I wrote this when I thought I was going to have a bunch more E2E tests, and this is over-engineered for the single test we ended up deciding on. So I'll combine SRTestBase and E2ETestBase into a single base class.

2024-08-21 06:15 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestBase.cs
> +	public class SRTestBase
Done in commit 5c7059b.

2024-08-21 09:35 UTC, hahn-kev requested changes
left some more feedback for this PR.

2024-08-21 09:35 UTC, hahn-kev commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +		private Guid? ProjectIdToDelete { get; set; }
better yet these Ids come from the test environment which needs to be disposed. It should internally track created projects rather than doing that stuff here.

2024-08-21 09:35 UTC, hahn-kev commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
>  		private TemporaryFolder TempFolder { get; init; }
if I understand what these temp folders are for then this class should dispose of them once it's disposed of

2024-08-21 09:35 UTC, hahn-kev commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +			if (nonSuccess == 0) TempFolderForClass.Dispose();
I think this means that because we ignore the tests when lexbox is not available that we don't cleanup the temp folder, is that right?

2024-08-21 09:35 UTC, hahn-kev commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +			Assert.That(result.Id, Is.EqualTo(randomGuid));
you've got this assert duplicated above in the create empty project method. Would it make sense to move these asserts into the `TestEnv.CreateLexBoxProject` method?

2024-08-21 09:35 UTC, hahn-kev commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +			client.AdditionalHeaders["cookie"] = authCookie;
I was really surprised that we can't just reuse our http client meaning we don't need to pass the cookies like this, so I looked into this TusClient and it looks like it hasn't been updated in 4 years and uses WebRequest under the covers, so I did a search and found this modern client https://www.nuget.org/packages/BirdMessenger which uses http client meaning we can just pass ours in and do away with copying cookies around.

2024-08-22 02:39 UTC, rmunn commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +			if (nonSuccess == 0) TempFolderForClass.Dispose();
According to https://docs.nunit.org/articles/nunit/technical-notes/usage/Counting-Tests.html, ignored tests increment result.SkipCount, which I'm NOT including in the `nonSuccess` counter. So if lexbox is not available and those tests are ignored (but all other tests passed), then `nonSuccess` will be 0 and the temp folder will be cleaned up.

2024-08-22 02:41 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
>  		private TemporaryFolder TempFolder { get; init; }
This one is just set to the base class's `_languageForgeServerFolder` field, which is already disposed by the base class. I suppose I could just not have this property and use `_languageForgeServerFolder` everywhere, but it seemed nicer to have a better name for it.

So this one is already being disposed and doesn't need to be disposed again.

2024-08-22 02:45 UTC, rmunn commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +			Assert.That(result.Id, Is.EqualTo(randomGuid));
Done in commit 0af5fb2.

2024-08-22 02:50 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +			client.AdditionalHeaders["cookie"] = authCookie;
Great, I'll use that. Projects that haven't been updated in more than a year or two always make me nervous, because what security vulnerability is going to go unpatched for years? Thanks for finding that more recently-updated project.

2024-08-22 03:26 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +			client.AdditionalHeaders["cookie"] = authCookie;
OK, done in commit b3e258d.

2024-08-22 03:36 UTC, rmunn commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +		public async Task TestTeardown()
Done in commit 5fe1d6d.

2024-08-22 03:38 UTC, rmunn commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +		public TemporaryFolder LcmDataFolder { get; set; }
Yep, they could be path strings. I used to use TestDataFolder elsewhere, but I seem to have ended up not needing that code so it got removed. LcmDataFolder was just for symmetry, but it too could be a path string.

2024-08-22 03:49 UTC, rmunn commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +		public TemporaryFolder LcmDataFolder { get; set; }
Done in commit 52017e9.

2024-08-22 04:30 UTC, rmunn commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +		public FwProject CloneFromLexbox(string code, string? newCode = null, TimeSpan? waitTime = null)
Renamed to be more clear in commit 1eea903.

2024-08-22 04:46 UTC, rmunn commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +		private Guid? ProjectIdToDelete { get; set; }
Made it a HashSet in commit 0d1e52f so that multiple projects can be deleted if necessary. I'd rather track this in the test class rather than the environment, because the decision of whether to delete the test IDs or not depends on whether the test succeeded.

2024-08-26 04:54 UTC, hahn-kev commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +		public TemporaryFolder LcmDataFolder { get; set; }
ok so can these properties be removed now?

2024-08-26 05:00 UTC, hahn-kev requested changes
left 2 requests. Otherwise it's looking almost done

2024-08-26 05:00 UTC, hahn-kev commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +			var fileStream = new FileStream(file.FullName, FileMode.Open, FileAccess.Read);
I think this stream needs to be disposed. It doesn't look like tus does that for you.

2024-08-26 06:26 UTC, rmunn commented on src/LfMerge.Core.Tests/E2E/E2ETestBase.cs
> +		public TemporaryFolder LcmDataFolder { get; set; }
Whoops, didn't actually remove the properties, only their usage. Removed in commit 68440129.

2024-08-26 06:44 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +			var fileStream = new FileStream(file.FullName, FileMode.Open, FileAccess.Read);
Done in commit 0f10f6b6.

2024-08-26 08:01 UTC, hahn-kev approved these changes
Looks good, we will enable these to run on CI in another PR

2024-08-26 08:11 UTC, merged