Refactor SyncAction tests to use real FwProjects pushing to local Mercurial server
sillsdev/LfMerge pull request #347
Opened 2024-08-20 05:34 UTC by rmunn

WIP. Will fix #346 when completed.

Currently there's one sample test that creates a new FwProject from the included testlangproj data, then makes a modification and pushes it to the mock LD server (a copy of Mercurial running `hg serve`).

Next up: turning that into a real test that does a Send/Receive, then coverting the SyncAction tests to use that method as it's far easier to see what the setup is.

2024-08-21 08:00 UTC, rmunn commented
There's one more test, SynchronizeAction_CustomReferenceAtomicField_DoesNotThrowExceptionDuringSync, which could in theory be converted to use FwProjects instead of the old approach. However, it's essentially a regression test: there used to be a bug in FieldWorks 8.x that was causing certain custom fields to throw an exception when the FW value was converted to Mongo. There's workaround code in LfMerge to avoid that FW bug, and the test is verifying that with the workaround in place, those custom fields can be imported without error.

Thing is, apparently the FW bug was fixed at some point between 8.x and 9.x, because when I removed the LfMerge workaround code, the test continued to pass. So either I wrote that test wrong in the first place (doubtful), or else the liblcm code fixed the bug sometime in the past few years.

Which makes me a little cautious about making any changes to the regression test, as it was a rather complicated setup and since I can't make the test fail at the moment, I can't prove that any changes I make are still actually exercising the bug that used to be there.

So I've decided not to touch the SynchronizeAction_CustomReferenceAtomicField_DoesNotThrowExceptionDuringSync test. We might remove it in the future, but for now let's leave it in place as a regression test, to ensure that the FW bug doesn't come back.

2024-08-29 01:43 UTC, hahn-kev commented on src/LfMerge.Core.Tests/Actions/SynchronizeActionTests.cs
> +		public (string, DateTime, DateTime) UpdateLfEntry(LanguageForgeProject lfProject, Guid entryId, Func<LfLexEntry, LfStringField> getField, Func<string, string> textConverter)
there's a lot of duplicated code between the 2 overloads of this function. Can you just make this one call the version with `Action updater`?

2024-08-29 01:43 UTC, hahn-kev commented on src/LfMerge.Core.Tests/Actions/SynchronizeActionTests.cs
> +		public (DateTime, DateTime) DeleteLfEntry(LanguageForgeProject lfProject, Guid entryId)
this could also just call `UpdateLfEntry` and mark the entry as deleted in the updater

2024-08-29 01:54 UTC, hahn-kev requested changes
left a couple comments. Something that I realized looking at the verification code. In these Synchronize tests we're only verifying against the mongo db. Is there another test class where we verify what changes were applied to the FW Project?

2024-09-02 02:30 UTC, rmunn commented on src/LfMerge.Core.Tests/Actions/SynchronizeActionTests.cs
> +		public (string, DateTime, DateTime) UpdateLfEntry(LanguageForgeProject lfProject, Guid entryId, Func<LfLexEntry, LfStringField> getField, Func<string, string> textConverter)
Done.

2024-09-02 02:30 UTC, rmunn commented on src/LfMerge.Core.Tests/Actions/SynchronizeActionTests.cs
> +		public (DateTime, DateTime) DeleteLfEntry(LanguageForgeProject lfProject, Guid entryId)
Done.

2024-09-04 01:52 UTC, hahn-kev approved these changes

2024-09-27 06:53 UTC, rmunn commented
Build was failing because it was building against the potential merge commit, where I had changed one API in the MongoConnectionDouble class. I hadn't noticed the API change because when I tested locally, I was running against the branch head, not the potential merge commit. So GitHub's default PR target just helped me NOT break the `develop` branch once the PR is merged!

2024-09-27 07:08 UTC, merged