Use real MongoDB connection for E2E tests
sillsdev/LfMerge pull request #348
Opened 2024-08-23 01:58 UTC by rmunn

Fixes #345.

The end-to-end LfMerge tests now use a real MongoDB container (spun up and torn down for each test, with no data persistence) rather than a mock Mongo connection. This does require the presence of Docker on the machine running the E2E tests, so that `docker run mongo:6` will succeed.

2024-08-27 03:41 UTC, hahn-kev requested changes
the main change I would like is to always cleanup the mongo container, and to throw if mongo fails to start

2024-08-27 03:41 UTC, hahn-kev commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +		public void LaunchMongo()
it looks like this method will mostly fail silently making tests fail in unexpected ways. This method should throw if it can't launch mongo

2024-08-27 03:41 UTC, hahn-kev commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +						Console.WriteLine($"Leaving Mongo container {MongoContainerId} around to examine data on failed test.");
I don't really like the idea of leaving the container around as it means if there's a bug and you're trying to fix a test and you run it repeatedly you're going to end up with a bunch of containers which you must stop yourself. I'd rather have a flag that we can manually enable to keep the container around, otherwise it should always be killed.

2024-08-27 03:41 UTC, hahn-kev commented on src/LfMerge.Core/Settings/LfMergeSettings.cs
> +		public string MongoDbHostNameAndPort { get { return String.Format("{0}:{1}", MongoHostname, MongoPort); } }
```suggestion
		public string MongoDbHostNameAndPort => $"{MongoHostname}:{MongoPort}";
```

2024-08-27 03:41 UTC, hahn-kev commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +						Settings.MongoPort = parts[1];
should we attempt to connect to the db to ensure it's up before we return from this method?

2024-08-27 06:32 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +		public void LaunchMongo()
Done in commit 48f4608.

2024-08-27 06:32 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +						Console.WriteLine($"Leaving Mongo container {MongoContainerId} around to examine data on failed test.");
Done in commit 48f4608, except for the flag.

2024-08-27 06:32 UTC, rmunn commented on src/LfMerge.Core/Settings/LfMergeSettings.cs
> +		public string MongoDbHostNameAndPort { get { return String.Format("{0}:{1}", MongoHostname, MongoPort); } }
Done in commit 48f4608.

2024-08-27 06:35 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +						Settings.MongoPort = parts[1];
I'd rather not. The MongoClient class from the Mongo C# drivers already has a timeout of 40 seconds to connect to Mongo, and before any Mongo connection is attempted, there is going to be several seconds' worth of setup in Lexbox: downloading a backup zip of sena-3, creating a new project, resetting the project and uploading the backup zip... The time that takes is sufficient so that I've never had an issue with Mongo not being up by the time the test needs it, and even if Mongo isn't quite finished going up yet, the MongoClient will wait 40 seconds already which is enough to get Mongo up. I wouldn't expect any test failures from Mongo not being ready in time.

2024-08-27 06:40 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +						Console.WriteLine($"Leaving Mongo container {MongoContainerId} around to examine data on failed test.");
Flag implemented in commit 563a0a2.

2024-08-27 07:05 UTC, hahn-kev commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +				if (CleanUpTestData || !string.IsNullOrEmpty(Environment.GetEnvironmentVariable(MagicStrings.EnvVar_E2E_LeaveMongoContainerRunningOnFailure))) {
this would mean that `LFMERGE_E2E_LEAVE_MONGO_CONTAINER_RUNNING_ON_FAILURE =false` would be considered enabled

2024-08-27 07:07 UTC, hahn-kev requested changes
looks good, I'd like to allow setting `LFMERGE_E2E_LEAVE_MONGO_CONTAINER_RUNNING_ON_FAILURE` to false should disable it. Otherwise it's good to go

2024-08-28 01:08 UTC, rmunn commented on src/LfMerge.Core.Tests/SRTestEnvironment.cs
> +				if (CleanUpTestData || !string.IsNullOrEmpty(Environment.GetEnvironmentVariable(MagicStrings.EnvVar_E2E_LeaveMongoContainerRunningOnFailure))) {
In commit 95e29ea I allow a value of "false" or "0" to also be counted as disabled. (0 because a lot of Microsoft's stuff suggests setting DOTNET_ENV_VAR to 1 to enable it, so 0 is a natural "disabled" meaning). I stopped short of treating "f" and "n" and "no" as false values, though that would of course be quite easy to add given the refactoring I did in 95e29ea.

2024-08-28 09:03 UTC, hahn-kev approved these changes

2024-08-29 03:04 UTC, merged